USE SGF;
GO
IF EXISTS(SELECT * FROM sysobjects WHERE NAME = 'SGF_PROC_GET_MOVEMENT_TYPES' AND XTYPE='P')
	DROP PROCEDURE SGFADM.SGF_PROC_GET_MOVEMENT_TYPES;
GO
CREATE PROCEDURE SGFADM.SGF_PROC_GET_MOVEMENT_TYPES
/*INPUT
NONE	
Example exec SGF_PROC_GET_MOVEMENT_TYPES
*/
AS
BEGIN
	SELECT 
		MT.MOV_TYPE_ID,
		MT.DESCRIPTION AS MOV_TYPE_DES,
		C.CAT_ID AS CATEGORY_ID,
		C.DESCRIPTION AS CATEGORY_DES,
		SC.SUB_CAT_ID AS SUB_CATEGORY_ID,
		SC.DESCRIPTION AS SUB_CATEGORY_DES
	FROM 
		SGF_R_MOVEMENT_TYPE MT	LEFT JOIN SGF_R_CATEGORY C ON MT.MOV_TYPE_ID = C.MOV_TYPE_ID
								LEFT JOIN SGF_R_SUB_CATEGORY SC ON C.CAT_ID = SC.CAT_ID
	ORDER BY MT.MOV_TYPE_ID, C.CAT_ID, SC.SUB_CAT_ID
END
GO	

GO
GRANT EXEC ON OBJECT::SGFADM.SGF_PROC_GET_REPORT_BY_CATEGORIES TO sgf_app;