//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SGFResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SGFResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SGFResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string AccountsDialogTitleMsgDelete {
            get {
                return ResourceManager.GetString("AccountsDialogTitleMsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this account?.
        /// </summary>
        internal static string AccountsMsgDelete {
            get {
                return ResourceManager.GetString("AccountsMsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string AccountsPageTitle {
            get {
                return ResourceManager.GetString("AccountsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string ActionRegister {
            get {
                return ResourceManager.GetString("ActionRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Account.
        /// </summary>
        internal static string ActionSaveBankAccount {
            get {
                return ResourceManager.GetString("ActionSaveBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Default Language.
        /// </summary>
        internal static string AppLang {
            get {
                return ResourceManager.GetString("AppLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGF - Personal Finance System Management.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string DataTableLabel1 {
            get {
                return ResourceManager.GetString("DataTableLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string DataTableLabel2 {
            get {
                return ResourceManager.GetString("DataTableLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubCategory.
        /// </summary>
        internal static string DataTableLabel3 {
            get {
                return ResourceManager.GetString("DataTableLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string DataTableLabel4 {
            get {
                return ResourceManager.GetString("DataTableLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DataTableLabel5 {
            get {
                return ResourceManager.GetString("DataTableLabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DataTableLabel6 {
            get {
                return ResourceManager.GetString("DataTableLabel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string DisplayAccountName {
            get {
                return ResourceManager.GetString("DisplayAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string DisplayAccountNumber {
            get {
                return ResourceManager.GetString("DisplayAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string DisplayBalance {
            get {
                return ResourceManager.GetString("DisplayBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string DisplayBankName {
            get {
                return ResourceManager.GetString("DisplayBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string DisplayConfirmPassword {
            get {
                return ResourceManager.GetString("DisplayConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string DisplayEmail {
            get {
                return ResourceManager.GetString("DisplayEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language preference.
        /// </summary>
        internal static string DisplayLanguage {
            get {
                return ResourceManager.GetString("DisplayLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality of origin.
        /// </summary>
        internal static string DisplayNationality {
            get {
                return ResourceManager.GetString("DisplayNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string DisplayNewPassword {
            get {
                return ResourceManager.GetString("DisplayNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string DisplayOldPassword {
            get {
                return ResourceManager.GetString("DisplayOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Info.
        /// </summary>
        internal static string DisplayOtherInfo {
            get {
                return ResourceManager.GetString("DisplayOtherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string DisplayPassword {
            get {
                return ResourceManager.GetString("DisplayPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string DisplayRememberMe {
            get {
                return ResourceManager.GetString("DisplayRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string DisplayUsername {
            get {
                return ResourceManager.GetString("DisplayUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ErroMsgLogOnUsername {
            get {
                return ResourceManager.GetString("ErroMsgLogOnUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string FlagFrance {
            get {
                return ResourceManager.GetString("FlagFrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string FlagPortugal {
            get {
                return ResourceManager.GetString("FlagPortugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string FlagSpain {
            get {
                return ResourceManager.GetString("FlagSpain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English - United States.
        /// </summary>
        internal static string FlagUsa {
            get {
                return ResourceManager.GetString("FlagUsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string Graph1DataLabel1 {
            get {
                return ResourceManager.GetString("Graph1DataLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string Graph1DataLabel2 {
            get {
                return ResourceManager.GetString("Graph1DataLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Month.
        /// </summary>
        internal static string Graph1Title {
            get {
                return ResourceManager.GetString("Graph1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string Graph2DataLabel1 {
            get {
                return ResourceManager.GetString("Graph2DataLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string Graph2DataLabel2 {
            get {
                return ResourceManager.GetString("Graph2DataLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Month.
        /// </summary>
        internal static string Graph2Title {
            get {
                return ResourceManager.GetString("Graph2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string Graph3DataLabel1 {
            get {
                return ResourceManager.GetString("Graph3DataLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string Graph3DataLabel2 {
            get {
                return ResourceManager.GetString("Graph3DataLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Year.
        /// </summary>
        internal static string Graph3Title {
            get {
                return ResourceManager.GetString("Graph3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Graph4DataLabel1 {
            get {
                return ResourceManager.GetString("Graph4DataLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Graph4Title {
            get {
                return ResourceManager.GetString("Graph4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Graph5DataLabel1 {
            get {
                return ResourceManager.GetString("Graph5DataLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubCategories.
        /// </summary>
        internal static string Graph5Title {
            get {
                return ResourceManager.GetString("Graph5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance :.
        /// </summary>
        internal static string IndexBalanceLabel {
            get {
                return ResourceManager.GetString("IndexBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number / Bank.
        /// </summary>
        internal static string IndexOptionLabel {
            get {
                return ResourceManager.GetString("IndexOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string IndexPageTitle {
            get {
                return ResourceManager.GetString("IndexPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        internal static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user name and password..
        /// </summary>
        internal static string LogOnMsg {
            get {
                return ResourceManager.GetString("LogOnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Finance System Management.
        /// </summary>
        internal static string LogOnPageTitle {
            get {
                return ResourceManager.GetString("LogOnPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string LogOnValidation {
            get {
                return ResourceManager.GetString("LogOnValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string OpAdd {
            get {
                return ResourceManager.GetString("OpAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string OpDelete {
            get {
                return ResourceManager.GetString("OpDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string OpEdit {
            get {
                return ResourceManager.GetString("OpEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string OpNo {
            get {
                return ResourceManager.GetString("OpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string OpSave {
            get {
                return ResourceManager.GetString("OpSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Please select an account --.
        /// </summary>
        internal static string OptionSelectAccount {
            get {
                return ResourceManager.GetString("OptionSelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Please select a language --.
        /// </summary>
        internal static string OptionSelectLanguage {
            get {
                return ResourceManager.GetString("OptionSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Please select a nationality --.
        /// </summary>
        internal static string OptionSelectNationality {
            get {
                return ResourceManager.GetString("OptionSelectNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string OpYes {
            get {
                return ResourceManager.GetString("OpYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        internal static string PasswordResetMsg {
            get {
                return ResourceManager.GetString("PasswordResetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t remember your password..
        /// </summary>
        internal static string PasswordResetMsg2 {
            get {
                return ResourceManager.GetString("PasswordResetMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an Account.
        /// </summary>
        internal static string RegisterAccountBankPageTitle {
            get {
                return ResourceManager.GetString("RegisterAccountBankPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        internal static string RegisterAccountBankst1 {
            get {
                return ResourceManager.GetString("RegisterAccountBankst1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        internal static string RegisterAccountst1 {
            get {
                return ResourceManager.GetString("RegisterAccountst1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to create a new account..
        /// </summary>
        internal static string RegisterAccountst2 {
            get {
                return ResourceManager.GetString("RegisterAccountst2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are required to be a minimum of {0}  characters in length..
        /// </summary>
        internal static string RegisterAccountst3 {
            get {
                return ResourceManager.GetString("RegisterAccountst3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string RegisterAccountst4 {
            get {
                return ResourceManager.GetString("RegisterAccountst4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string RegisterAccountst5 {
            get {
                return ResourceManager.GetString("RegisterAccountst5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Date.
        /// </summary>
        internal static string RegisterMovementLabelDtFim {
            get {
                return ResourceManager.GetString("RegisterMovementLabelDtFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date.
        /// </summary>
        internal static string RegisterMovementLabelDtIni {
            get {
                return ResourceManager.GetString("RegisterMovementLabelDtIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string RegisterMovementLabelExport {
            get {
                return ResourceManager.GetString("RegisterMovementLabelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string RegisterMovementLabelSearch {
            get {
                return ResourceManager.GetString("RegisterMovementLabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movements.
        /// </summary>
        internal static string RegisterMovementPageTitle {
            get {
                return ResourceManager.GetString("RegisterMovementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  if you don&apos;t have an account..
        /// </summary>
        internal static string RegisterMsg {
            get {
                return ResourceManager.GetString("RegisterMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportsPageTitle {
            get {
                return ResourceManager.GetString("ReportsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
